### ISSUE TITLE
I seeeeeeeeeeeeeeee

### ISSUE THREAD

**Issue by szepeviktor** [danielbachhuber/wordpress-playground-vscode#1]
"vs-code" in wordpress-playground-vs-code does not mean "versus code" but Visual Studio Code

Please consider changing the name to `wordpress-playground-vscode`

Thank you!

**Comment by szepeviktor** [comment]
Done 🍏
`https://github.com/danielbachhuber/wordpress-playground-vscode`

**Comment by danielbachhuber** [comment]
@szepeviktor It started bugging me too 😊
